# Generated by Django 5.0 on 2024-06-02 12:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('story', ckeditor.fields.RichTextField()),
                ('image_name', models.ImageField(upload_to='movies')),
                ('image_cover', models.ImageField(upload_to='movies')),
                ('date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ManyToManyField(to='anime.category')),
            ],
        ),
    ]
