# Generated by Django 5.0 on 2024-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
