# Generated by Django 5.0 on 2024-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_remove_anime_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
